[package]
name = "dungeons-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "dungeons"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
