// This file is autogenerated.
use super::engine::types::{Sprite, Color::*};
pub const SLIME: Sprite = [
    [Black, Black, Black, Black, Black, Black, Black, Black, ],
    [Black, Black, Black, Black, Black, Black, Black, Black, ],
    [Black, Black, Red, Red, Red, Black, Black, Black, ],
    [Black, Red, White, Red, Red, Red, Black, Black, ],
    [Red, White, Red, Red, Red, Red, Red, Black, ],
    [Red, Red, Red, Red, Red, Red, Red, Black, ],
    [Black, Red, Red, Red, Red, Red, Black, Black, ],
    [Black, Black, Black, Black, Black, Black, Black, Black, ],
];
